name: Spigot Discord Stripped
version: '${project.version}'
main: com.beanbeanjuice.spigotdiscordstripped.SpigotDiscordStripped
api-version: 1.18
load: STARTUP
authors: [ beanbeanjuice ]
description: A Stripped Discord to Minecraft Chat Integration
website: https://www.github.com/beanbeanjuice/spigot-discord-stripped
